[project]
name = "cargo-marketplace"
version = "0.1.0"
description = ""
authors = [
    {name = "Irshod",email = "aqdodovirshod7@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi (>=0.140.13,<0.141.0)",
    "uvicorn (>=0.52.0,<0.53.0)",
    "sqlalchemy (>=2.0.51,<3.0.0)",
    "asyncpg (>=0.31.0,<0.32.0)",
    "alembic (>=1.18.5,<2.0.0)",
    "pydantic (>=2.13.4,<3.0.0)",
    "pydantic-settings (>=2.14.2,<3.0.0)",
    "structlog (>=26.1.0,<27.0.0)",
    "redis (>=8.0.1,<9.0.0)",
    "python-jose (>=3.5.0,<4.0.0)",
    "argon2-cffi (>=25.1.0,<26.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest-asyncio (>=1.4.0,<2.0.0)",
    "ruff (>=0.16.0,<0.17.0)",
    "black (>=26.5.1,<27.0.0)"
]
